/icp_registration:
  ros__parameters:
    use_sim_time: false 
    rough_leaf_size: 0.4
    refine_leaf_size: 0.1
    #pcd_path: "/home/jlcv30/NUDT_navigation/src/rm_localization/faster-lio/PCD/306_3.pcd"
    pcd_path: "/home/suja/voxel_ws/test.pcd"
    map_frame_id: "map"
    odom_frame_id: "odom"
    laser_frame_id: "livox_frame"
    pointcloud_topic: "/cloud_registered_body"
    thresh: 1.0
    xy_offset: 0.5
    yaw_offset: 30.0
    yaw_resolution: 10.0
    initial_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # x,y,z,roll,pitch,yaw
